# install Odoo
- debug:
    msg: Odoo will be installed on {{ ansible_distribution }} 

- include: "{{ansible_os_family}}.yml"

# configure Odoo
- name: Config Odoo
  copy:
    src: odoo.conf
    dest: /etc/odoo/

- name: Started Odoo
  service:
    name: odoo
    state: restarted
    enabled: yes

- name: Started PostgreSQL
  service:
    name: postgresql
    state: started
    enabled: yes

# set soft link, -b over
- name: set soft link
  shell: |
    ln -sf /usr/lib/python3/dist-packages/odoo  /data/wwwroot
    ln -sf /etc/odoo/odoo.conf /data/config
    ln -sf /var/log/odoo /data/logs

# display version and service state of components
- name: Get odoo version
  shell: sudo sh -c "odoo --version 1>> /data/logs/install_version.txt"

- name: Check odoo Service
  shell: systemctl status odoo | grep Active*
  register: check_odoo_service
  notify: check_odoo_service
