# CentOS does not have the minimum Python requirements (3.5) for Odoo
# 添加Software Collections (SCL) 安装 Python
# This playbook can not run now

- name: Install Python3.5 for CentOS 
  shell: |
    yum -y install centos-release-scl
    yum -y install rh-python36
 
- name: Install System Required
  shell: |
    sudo yum install python3 python3-devel git gcc redhat-rpm-config libxslt-devel bzip2-devel openldap-devel libjpeg-devel freetype-devel -y
    git clone https://github.com/odoo/odoo.git --depth 1 --branch 14.0 /opt/odoo14
    cd /opt/odoo14/
    pip3 install -r requirements.txt

- block:
  - name: add Odoo Repository
    get_url:
      url: https://nightly.odoo.com/{{odoo_version}}/nightly/rpm/odoo.repo
      dest: /etc/yum.repos.d
