---
- name: Pre_tasks of Odoo
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: False
  pre_tasks:
   - name: 'install python'
     raw: 'sudo apt-get -y install python'

- ame: Odoo
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - {role: common, tags: "common"}
    - {role: nginx, tags: "nginx"}
    - {role: odoo, tags: "odoo"}
    - {role: end, tags: "end"}