---
- name: Pre_tasks of Odoo
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: False
  pre_tasks:
   - name: 'install python'
     raw: 'sudo apt update && sudo apt-get -y install python'
     ignore_errors: True

- name: Odoo
  hosts: all
  become: yes
  become_method: sudo
  vars_files:
    - variables.yml
  
  roles:
    - {role: common, tags: "common"}
    - {role: cloud, tags: "cloud"}
    - {role: nginx, tags: "nginx"}
    - {role: odoo, tags: "odoo"}
    - {role: end, tags: "end"}